spring.application.name=billetterie

spring.datasource.url=jdbc:postgresql://localhost:5432/billetterie

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
